server:
  port: 8989
  servlet:
    context-path: /start
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?characterEncoding=utf-8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  redis:
    host: 192.168.161.10
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
  data:
    elasticsearch:
      cluster-name: my-es
      cluster-nodes: 192.168.161.20:9300
      repositories:
        enabled: true
mybatis:
  mapper-locations: com/baizhi/mapper/*.xml